<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="diff_car">

  <!-- 参数定义 -->
  <xacro:property name="body_length" value="0.70"/> <!-- m -->
  <xacro:property name="body_width"  value="0.70"/>
  <xacro:property name="body_height" value="0.10"/>
  <xacro:property name="body_mass"   value="10"/>

  <xacro:property name="wheel_radius" value="0.05"/> <!-- 10 cm -->
  <xacro:property name="wheel_width"  value="0.05"/>
  <xacro:property name="wheel_mass"   value="1"/>
  <xacro:property name="ground_clearance" value="0.03"/>

  <!-- 惯性宏: box -->
  <xacro:macro name="box_inertia" params="mass x y z">
    <!-- 立方体惯性矩 -->
    <inertial>
      <mass value="${mass}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="${1/12.0*mass*(y*y+z*z)}"
               iyy="${1/12.0*mass*(x*x+z*z)}"
               izz="${1/12.0*mass*(x*x+y*y)}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </xacro:macro>

  <!-- 惯性宏: cylinder -->
  <xacro:macro name="cylinder_inertia" params="mass r l">
    <!-- 圆柱体惯性矩 -->
    <inertial>
      <mass value="${mass}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="${1/12.0*mass*(3*r*r + l*l)}"
               iyy="${1/12.0*mass*(3*r*r + l*l)}"
               izz="${0.5*mass*r*r}"
               ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </xacro:macro>

  <link name="base_foot_link">
    <visual>
      <geometry>
        <sphere radius="0.01" />
      </geometry>
      <material name="blue">
        <color rgba="0.2 0.2 0.8 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <sphere radius="0.01" />
      </geometry>
    </collision>
  </link>


  <!-- ================== 车体 ================== -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.2 0.2 0.8 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia mass="${body_mass}"
                       x="${body_length}" y="${body_width}" z="${body_height}"/>
  </link>


    <joint name="base_link_to_base_foot_link" type="fixed">
      <parent link="base_foot_link"/>
      <child link="base_link"/>
      <origin xyz="0 0 ${body_height/2 + ground_clearance}" rpy="0 0 0"/>
    </joint>


  <!-- ================== 四个轮子 ================== -->
  <xacro:macro name="wheel" params="name x y z">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <!-- 将圆柱转90°，x轴为轴向 -->
        <origin xyz="0 0 0" rpy="0 1.5708 0"/>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 1.5708 0"/>
      </collision>
      <xacro:cylinder_inertia mass="${wheel_mass}" r="${wheel_radius}" l="${wheel_width}"/>
    </link>

    <joint name="joint_${name}" type="continuous">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
      <axis xyz="1 0 0"/>
    </joint>
  </xacro:macro>

  <!-- 车体中心到轮子中心的偏移 -->
  <xacro:property name="wheel_offset_x" value="0.38"/> <!-- m -->
  <xacro:property name="wheel_offset_y" value="0.25"/>
  <xacro:property name="wheel_center_z"
                  value="${-body_height/2 - ground_clearance + wheel_radius }"/>

  <!-- 实例化四个轮子 -->
  <xacro:wheel name="wheel_fl" x="${ wheel_offset_x}" y="${ wheel_offset_y}" z="${wheel_center_z}"/>
  <xacro:wheel name="wheel_fr" x="${ wheel_offset_x}" y="${-wheel_offset_y}" z="${wheel_center_z}"/>
  <xacro:wheel name="wheel_rl" x="${-wheel_offset_x}" y="${ wheel_offset_y}" z="${wheel_center_z}"/>
  <xacro:wheel name="wheel_rr" x="${-wheel_offset_x}" y="${-wheel_offset_y}" z="${wheel_center_z}"/>

</robot>
