# 障碍物层配置
obstacle_layer:
  enabled: true
  max_obstacle_height: 0.6      # 最大障碍物高度 (米)
  obstacle_range: 2.5           # 障碍物检测范围 (米)
  raytrace_range: 3.0            # 传感器光线追踪范围 (米)
  observation_sources: scan      # 数据源 (激光雷达)
  scan:
    topic: /scan                 # 激光雷达话题
    data_type: LaserScan         # 数据类型
    marking: true               # 是否标记障碍物
    clearing: true               # 是否清除自由空间
    expected_update_rate: 0.5    # 预期数据更新频率 (Hz)

# 膨胀层配置
inflation_layer:
  enabled: true
  inflation_radius: 0.5          # 膨胀半径 (米)
  cost_scaling_factor: 10.0      # 代价值缩放因子
  inflate_unknown: false        # 是否膨胀未知区域

# 通用参数
footprint: [[-0.3, -0.3], [-0.3, 0.3], [0.3, 0.3], [0.3, -0.3]]  # 机器人轮廓 (多边形)
transform_tolerance: 0.5         # TF变换容忍时间 (秒)