global_costmap:
  global_frame: map_2d               # 全局地图坐标系
  robot_base_frame: base_link      # 机器人基坐标系
  update_frequency: 1.0           # 地图更新频率 (Hz)
  publish_frequency: 0.5           # 可视化发布频率
  static_map: true                # 是否使用静态地图
  rolling_window: false           # 是否启用滚动窗口
  resolution: 0.05               # 分辨率需与local_costmap一致
  transform_tolerance: 1.0         # TF变换容忍时间
  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}