local_costmap:
  global_frame: camera_init              # 局部地图坐标系 (通常为odom)
  robot_base_frame: base_link     # 机器人基坐标系
  update_frequency: 2.0           # 地图更新频率 (Hz)
  publish_frequency: 2.0           # 可视化发布频率
  width: 30.0                      # 地图宽度 (米)
  height: 30.0                     # 地图高度 (米)
  resolution: 0.05                # 分辨率 (米/像素)
  rolling_window: true            # 是否启用滚动窗口
  transform_tolerance: 0.5         # TF变换容忍时间
  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}